name: recibopagos_app2app
description: Cliente Flutter para cobrar con la app ReciboPagos POS en el mismo equipo Android vía Intent (App To App).
version: 0.1.1
homepage: https://github.com/morello-cl/recibopagos_app2app
repository: https://github.com/morello-cl/recibopagos_app2app
documentation: https://recibopagos.com/desarrolladores/app-to-app
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: cl.mufin.recibopagos_app2app
        pluginClass: RecibopagosApp2appPlugin
